### ISSUE TITLE
Trying to get Requires2 to work, but I get compilation errors

### ISSUE THREAD

**Issue by virtualdogbert** [jbaumann/ASTTransformation-Requires#1] opened 2013-06-10 06:26 UTC
I found your blog post, and it seemed like a good way to get started with sending closures to ast transformations, but I get compilation errors(when running from grails 2.2), specifically around the:
methodCall {
    expression.add(closureAST)
    constant "call"
    argumentList {
    }
} 

The error I get is :
General error during semantic analysis: methodCall could not be invoked. Expected to receive parameters [class org.codehaus.groovy.ast.expr.Expression, class org.codehaus.groovy.ast.expr.Expression, class org.codehaus.groovy.ast.expr.Expression] but found []

Any ideas on how to get around it, because I'm just going in circles at this point?
I have tried the example outside of grails, in groovy 2.1.4, but the Requires2Example annotation throws this error:
Caught: groovy.lang.MissingPropertyException: No such property: divisor for class: Requires2Example

**Comment by virtualdogbert** [comment] 2013-10-13 23:30
I don't think anyone is looking at this and I figured out how to get the same effect in a different way.

**Comment by kriegaex** [comment] 2020-03-29 06:56
@virtualdogbert, I cannot get it running on Groovy 2.4.x either. Do you have a working version (fork or similar project) of this one and/or can elaborate what you mean by:

> I figured out how to get the same effect in a different way

BTW, `RequiresTransformTestHelperTest` also fails:

```none
BUG! exception in phase 'conversion' in source unit '(...)RequiresExample.groovy' unexpected NullpointerException
	(...)
	at de.scrum_master.groovy_ast.RequiresTransformTestHelperTest.testInvokeUnitTest(RequiresTransformTestHelperTest.groovy:15)
	(...)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	(...)
	at de.scrum_master.groovy_ast.RequiresTransformation.visit(RequiresTransformation.groovy:38)
	(...)
```

Did you hit that one too?

**Comment by virtualdogbert** [comment] 2020-03-29 14:06
Wow was that really seven years ago... Well I made my own project which is a Grails plugin called Enforcer:
https://github.com/virtualdogbert/Enforcer

Instead of trying to invoke the closure in the AST transform, I took the easy way and delegated to a method in a service that would take the closures as params. I also learned about the VariableScopeVisitor to fix variable scope of the closure. I also later ran into an issue with mixing my transform with compile static, which made the project a bit more complicated. So here is a link before I added that complication:
https://github.com/virtualdogbert/Enforcer/tree/17d9b12ef35f99d07ae7fa100f17ef9c222bc640/src/main/groovy/com/virtualdogbert/ast

Hope this helps.

**Comment by kriegaex** [comment] 2020-03-30 00:54
> Hope this helps.

Thank you. Probably it would help tremendously if I would fully understand what I am doing, but I am a Java guy with some Spock-/Geb-based Groovy knowledge and just starting to look into AST transformations. Thus, I am not sure how and where in the code of `Requires2Transformation.visit(..)` to use a `VariableScopeVisitor` in order to make sure that the variable `divisor` in `@Requires2({divisor != a})` is getting resolved inside the method body because it is actually not referring to a variable defined in the scope of the annotation on the method body like `a` but to a method parameter unknown in that scope.

No matter what I might think about this way of programming - using internal state of a method in an annotation surrounding it - I guess back in the day it must have worked for the author of the blog post series, so I am just curious how to get it running with fairly up to date Groovy versions.

---

**Update:** Sorry, I was just stupid, adding the scope visitor to the wrong method `createStatements`, having scrolled too far in my editor. After I moved it to the end of `visit`, now the `@Requires2` transformation works:

```groovy
IfStatement block = createStatements(annotationExpression, sourceUnit)

def methodStatements = annotatedMethod.code.statements
methodStatements.add(0, block)

// Thanks to @virtualdogbert alias Tucker Pelletier
VariableScopeVisitor scopeVisitor = new VariableScopeVisitor(sourceUnit)
sourceUnit.AST.classes.each { ClassNode classNode ->
  scopeVisitor.visitClass(classNode)
}
```

---

Remains the `RequiresTransformTestHelperTest` not working. Any ideas there? This is actually about `@Requires`, not `@Requires2` and that transformation as such is working, as the other test proves (manual testing too). So it must be something about the way of testing as such, using the `TransformTestHelper` which might have changed internally since 2011. In this test the `visit(ASTNode[] astNodes, SourceUnit sourceUnit)` method gets an `astNode` value of `null`, which leads to the subsequent problem.

**Comment by kriegaex** [comment] 2020-03-30 01:30
Okay, I also figured out the `RequiresTransformTestHelperTest` root cause. Actually the information is hidden in the corresponding [blog post](http://joesgroovyblog.blogspot.com/2011/09/ast-transformations-testing-and-error.html):

> The interesting thing is, that this also registers a local transformation correctly. There is one caveat though: the **transformation** now is registered as a local and a global transformation that thus gets **triggered twice**. One call is as expected (the call for the local transformation), **the other call (as a global transformation) provides only the source unit and no AST nodes i.e., the first argument is null.** If you followed the defensive programming style, then you already check whether the AST nodes are provided and stop processing if not.

Unfortunately, the author did not take his own advice to program defensively and specifically did not run that test again after he had added error reporting to the AST. This leads to this call failing:

```groovy
addError("Internal error: expecting [AnnotationNode, AnnotatedNode] but got: " + Arrays.asList(astNodes), astNodes[0], sourceUnit);
```

Additional log output shows that the AST is indeed triggered twice, just as described in the blog post, and the global transformation comes without AST nodes. So we need the additional safeguard `if (astNodes)`:

```groovy
if (!checkNode(astNodes, annotationType)) {
  if (astNodes) {
    //From LogASTTransformation
    addError("Internal error: expecting [AnnotationNode, AnnotatedNode] but got: " + Arrays.asList(astNodes), astNodes[0], sourceUnit);
  }
  return
}
```

Now `RequiresTransformTestHelperTest` also runs as expected.

**Comment by virtualdogbert** [comment] 2020-03-30 01:41
Cool glad you figured it out. AST transforms are not for the faint of heart, and there is little help out there. A couple of years back I gave a talk about them at GR8 Conf.US Here are the slides from that. You might find something helpful in them. I definitely think getting IntelliJ up with a remote debugger can be very useful, but be prepared for it to be a bit buggy:
https://docs.google.com/presentation/d/1D4B0YQd0_0HYxK2FOt3xILM9XIymh-G-jh1TbQldbVA/edit#slide=id.g39ee7ff36c_1_213

**Comment by kriegaex** [comment] 2020-03-30 05:08
For what it is worth, in addition to PR #2 I also mavenised and modularised (AST vs test module) the project if you like to check it out in [my fork's master branch](https://github.com/kriegaex/ASTTransformation-Requires/tree/master). The project now
  * builds with Maven,
  * compiles and runs with Groovy 3.0.2,
  * tests with JUnit 4.12 (instead of using a deprecated legacy JUnit 3 test base class).

I thought I should return the favours received by publishing an updated version of this project.

**Comment by jbaumann** [comment] 2020-03-30 06:33
Sorry @virtualdogbert , I never got a mail regarding the original issue (wrong e-mail back then, I suppose). Sorry for that. And nice talk :-)
Regarding the problem: Yes, it definitely worked 9 years ago, but the compiler matured since then and probably one of the changes led to my code no longer working. And yes, I try to program defensively, but sooner or later the bugs get you...
@kriegaex you could add the mavenisation to the pull request and I‘ll add it as well.

**Comment by kriegaex** [comment] 2020-03-30 06:44
@jbaumann, along with the mavenisation I also moved all files from default package to `de.scrum_master.groovy_ast`, which is why I only did that on my fork's master. If you don't mind I can merge to the PR branch. Or you tell me your own preferred group ID and base package and I will change it for you on that branch.

Another PR for mavenisation would probably be even better. What do you think? You can also reach me for a chat on Gitter.

**Comment by jbaumann** [comment] 2020-03-30 06:57
If we are using a package (which makes sense), then I would use de.xinaris.groovy_ast, if that is ok. And yes, let us put this into a second PR.

**Closed as completed** 2020-03-30 07:00 UTC

**Comment by virtualdogbert** [comment] 2020-03-31 11:10
@jbaumann No worries, it pushed me to grow as a developer. Although it would have been nice to have anyone to talk to about the ASTs because they can be hard to figure out without some guidance or in my case persistence. 

Although in retrospect I technically couldn't use this project because there is no open-source license in the code. You may want to consider adding one of the following 
Appache2, MIT, BSD or whatever one strikes your fancy. I use Appache2 just because it was common in the Grails community, and allows people to pretty much do what they want with the code.

**Comment by jbaumann** [comment] 2020-03-31 11:16
This is actually a very good point (back then we didn't think about the licenses as much). I have added the Apache2-license, because I like it most and use it in other projects as well.
